version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  ingestion:
    build: ./apps/ingestion
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: ${RABBITMQ_URI}

  processor:
    build: ./apps/processor
    depends_on:
      - rabbitmq
      - mongo
    environment:
      RABBITMQ_URI: ${RABBITMQ_URI}
      MONGO_URI: ${MONGO_URI}
